source("data_generation.r")
library(ggplot2)
library(patchwork)
library(cowplot)


#' Generate gridded dataset draws
#'
#' @param nrows The number of columns
#' @param ncols The number of rows
#' @param paired Whether datasets should be paired or unpaired
#' @param ...  Additional arguments are passed on to gen_paired_data if paired=TRUE or gen_unpaired data otherwise
#'
#' @return data.frame
gen_gridded_dataset_draws <- function(nrows=3, ncols=3, paired = F, ...){
  rows = 1:nrows
  cols = 1:ncols
  
  between_neuron_vars <- seq(0.1,1,length=nrows)
  within_neuron_vars <- seq(0.1,1,length=ncols)
  
  datasets <- list()
  
  for (row in rows){
    for (col in cols){
      between <- between_neuron_vars[[row]]
      within <- within_neuron_vars[[col]]
      if(paired){
        dat<- gen_paired_data(between_neuron_sd = sqrt(between), within_neuron_sd = sqrt(within), ...)
      }else{      
        dat<- gen_unpaired_data(control_between_neuron_sd = sqrt(between), intervention_between_neuron_sd = sqrt(between),
                                          control_within_neuron_sd = sqrt(within), intervention_within_neuron_sd = sqrt(within), ...)
      }

      
      dat$between_neuron_variance <- between
      dat$within_neuron_variance  <- within
      
      datasets[[(row-1)*length(cols) + col]] <- dat
    }
  }
  
  
  longform_datasets <- Reduce(rbind, datasets)
}

#' Plot Gridded Dataset Draws
#' 
#' A figure demonstrating how the data generated by data_generation.R functions can vary. 
#'
#' @param longform_datasets A set of gridded datasets generated by gen_gridded_dataset_draws
#' @param marginalize_neurons If TRUE, amalgamate neurons together. If FALSE, plot each neuron seperately
#' @param cumulative If TRUE, draw the empirical cumulative probability distribution. If False, draw the empirical probability density
#' @param paired Whether the data contained in longform_datasets is paired or unpaired
#'
#' @return ggplot object
plot_gridded_dataset_draws <- function(longform_datasets, marginalize_neurons = FALSE, cumulative = FALSE, paired = F){
  library(ggplot2)

  plt <- ggplot(data = longform_datasets, aes(x = dependant, color = group))
  
  if (marginalize_neurons && !cumulative){
    plt <- plt + geom_density()
  }else if (marginalize_neurons && cumulative){
    plt <- plt + stat_ecdf(geom="step")
  }else{
    if(paired){
      plt <- plt + geom_density(aes(color=neuron_id, linetype = group))
    }else{
      #Keep all the neurons in a group the same color
      for (neuron in unique(longform_datasets$neuron_id)){
        plt <- plt + geom_density(data = longform_datasets[longform_datasets$neuron_id == neuron,])
        
      }
    }
  }
  
  plt <- plt + facet_grid(rows                    = vars(between_neuron_variance),               cols = vars(within_neuron_variance), 
                          labeller = label_bquote(rows=Var[between]==.(between_neuron_variance), cols = Var[within]==.(within_neuron_variance)))
  plt <- plt + labs(x = "Amplitude or Frequency", y=if(cumulative)"Cumulative Probability" else "Probability Density")
  plt <- plt + theme(legend.title = element_blank())
  plt <- plt + theme(strip.text.x = element_text(size = 11), strip.text.y =  element_text(size = 11))
  return(plt)
}

plot_cdf_pdf <- function(longform_datasets){
  df2 <- df[longform_datasets$within_neuron_variance==0.1,]
  df3 <- df[longform_datasets$within_neuron_variance==1,]
  
  col_names <- as_labeller(c("0.1" = "Var[between] == 0.1",  "0.55" = "Var[between] == 0.55", "1" = "Var[between] == 1"), default = label_parsed)
  
  
  common_theme <- theme(axis.title.x = element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), legend.position="none", plot.margin = unit(c(0,0.5,0,0), "cm"))
  common_theme_no_x_strip <- theme( axis.text=element_blank(), axis.ticks=element_blank(), legend.position="none", strip.text.x = element_blank(), plot.margin = unit(c(0,0.5,0,0), "cm"))
  
  cdf1 <-  ggplot(df2, aes(x=dependant, col=group)) + stat_ecdf(size=1) + facet_grid(cols=vars(between_neuron_variance), labeller=col_names  )
  cdf1 <- cdf1 + common_theme + scale_x_continuous(limits=c(-4,4))
  cdf1 <- cdf1 + labs(y="Cumulative Prob.")
  
  
  pdf1 <- ggplot(data = df2, aes(x = dependant, color = group))
  for (neuron in unique(df2$neuron_id)){
    pdf1 <- pdf1 + geom_density(data = df2[df2$neuron_id == neuron,], size=1)
  }
  pdf1 <- pdf1 + facet_grid(cols = vars(between_neuron_variance) )
  pdf1 <- pdf1 + common_theme_no_x_strip + scale_x_continuous(limits=c(-4,4))
  pdf1 <- pdf1 + labs(y="Prob. Density", x="Amplitude or Frequency")
  
  cdf2 <- ggplot(df3, aes(x=dependant, col=group)) + stat_ecdf(size=1) + facet_grid(cols=vars(between_neuron_variance), labeller=col_names)
  cdf2 <- cdf2 + common_theme  + scale_x_continuous(limits=c(-4,4))
  cdf2 <- cdf2 + labs(y="Cumulative Prob.")
  
  pdf2 <- ggplot(data = df3, aes(x = dependant, color = group))
  for (neuron in unique(df3$neuron_id)){
    pdf2 <- pdf2 + geom_density(data = df3[df3$neuron_id == neuron,], size=1)
  }
  pdf2 <- pdf2 + facet_grid(cols = vars(between_neuron_variance))
  pdf2 <- pdf2 + common_theme_no_x_strip + scale_x_continuous(limits=c(-4,4))
  pdf2 <- pdf2 + labs(y="Prob. Density", x="Amplitude or Frequency")
  
  
  
  top_grd <- plot_grid(cdf1, pdf1, nrow=2) + draw_label(expression(Var[within] == 0.1), x = 1.0, y=0.5, size=12, angle=270)
  bottom_grd <- plot_grid(cdf2, pdf2, nrow=2) + draw_label(expression(Var[within] == 1), x = 1.0, y=0.5, size=12, angle=270)
  
  grd <- plot_grid(top_grd, bottom_grd, nrow=2, scale = 0.95)
  
  return(grd)
}


show_treatment_effect_and_variance_difference <- function(marginalize_neurons = FALSE, cumulative = FALSE,...){
  

  
  no_treatment_effect <- gen_unpaired_data(treatment_effect = 0,
                                           control_within_neuron_sd = 1,
                                           intervention_within_neuron_sd = 1,
                                           ...)
  no_treatment_effect$type = "No Difference"
  treatment_effect <- gen_unpaired_data(treatment_effect = 2,
                                        control_within_neuron_sd = 1,
                                        intervention_within_neuron_sd = 1,
                                        ...)
  treatment_effect$type = "Different Means"
  variance_effect <- gen_unpaired_data(treatment_effect = 0,
                                       control_within_neuron_sd = 1,
                                       intervention_within_neuron_sd = 3,
                                       ...)
  variance_effect$type = "Different Standard Deviation"
  
  longform_datasets = rbind(no_treatment_effect, treatment_effect, variance_effect)
  
  longform_datasets$type <- factor(longform_datasets$type, c("No Difference", "Different Means", "Different Standard Deviation"))
  
  plt <- ggplot(data = longform_datasets, aes(x = dependant, color = group))
  
  if (marginalize_neurons && !cumulative){
    plt <- plt + geom_density()
  }else if (marginalize_neurons && cumulative){
    plt <- plt + stat_ecdf(geom="step")
  }else{
    for (neuron in unique(longform_datasets$neuron_id)){
      plt <- plt + geom_density(data = longform_datasets[longform_datasets$neuron_id == neuron,])
    }
  }
  plt <- plt + facet_grid(cols = vars(type), labeller = label_value)
  plt <- plt + theme(legend.title = element_blank(), panel.spacing.x = unit(4,"mm"))
  plt <- plt + labs(x = "Amplitude or Frequency", y = "Probability Density")
}
  

show_ideal_vs_realistic_paired_datasets <- function(){
  
  ideal <- gen_paired_data(between_neuron_sd = 1, within_neuron_sd = 0.2, n_neurons = 3, 
                           samples_per_neuron = 5000,between_pairmeans_sd = 0)
  
  realistic <- gen_paired_data(between_neuron_sd = 0.8, within_neuron_sd = 0.2, n_neurons = 3, 
                               samples_per_neuron = 5000,between_pairmeans_sd = 0.3)
  
  ideal$type <- "Idealised"
  realistic$type <- "Realistic"
  

  
  alldat <- rbind(ideal, realistic)
  
  neuron_mean_differences <- list()
  
  for (set in c("Idealised", "Realistic")){
    s <- subset(alldat, type==set)
    cntrl <- subset(s, group=="Control")
    neuron_cntrl_means <- tapply(cntrl$dependant, cntrl$neuron_id, mean)
    
    inter <- subset(s,group=="Intervention")
    neuron_inter_means <- tapply(inter$dependant, inter$neuron_id, mean)
    
    d <- data.frame(neuron_cntrl_means = neuron_cntrl_means, 
                    neuron_inter_means = neuron_inter_means,
                    neuron_id = unique(s$neuron_id),
                    type = set)
    
    neuron_mean_differences[[length(neuron_mean_differences)+1]] <- d
  }
  neuron_mean_differences <- do.call(rbind, neuron_mean_differences)

  
  plt <- ggplot(alldat, aes(x=dependant, color = neuron_id, linetype = group)) + geom_density()
  plt <- plt + geom_curve(data = neuron_mean_differences, aes(x = neuron_cntrl_means, xend = neuron_inter_means, y = 2, yend=2), 
                          linetype = "solid",
                          curvature = -0.2,
                          size = 1,
                          arrow = arrow(length=unit(0.3,'cm'), ends="last", type="closed"),
                          show.legend = F)
  plt <- plt + facet_grid(rows = vars(type))
  
  plt <- plt + labs(x = "Amplitude / Frequency", y = "Probability Density", color = "Neuron", linetype = "State")
  
  
                           
  return(plt)
}


show_sources_of_variance_in_paired_datasets <- function(){
  
  all_low <- gen_paired_data(n_neurons = 3, within_neuron_sd = 0.2, 
                             treatment_effect = 0, 
                             between_neuron_sd = 0.2, 
                             between_pairmeans_sd = 0.1,
                             samples_per_neuron = 5000)
  
  within <- gen_paired_data(n_neurons = 3, within_neuron_sd = 0.5, 
                            treatment_effect = 0, 
                            between_neuron_sd = 0.2, 
                            between_pairmeans_sd = 0.1,
                            samples_per_neuron = 5000)
  
  between <- gen_paired_data(n_neurons = 3, within_neuron_sd = 0.2, 
                             treatment_effect = 0, 
                             between_neuron_sd = 2, 
                             between_pairmeans_sd = 0.1,
                             samples_per_neuron = 5000)
  
  pairmeans <- gen_paired_data(n_neurons = 3, within_neuron_sd = 0.2, 
                               treatment_effect = 0, 
                               between_neuron_sd = 0.2, 
                               between_pairmeans_sd = 1,
                               samples_per_neuron = 5000)
  
  all_low$type = "low"
  within$type = "within"
  between$type = "between"
  pairmeans$type = "pairmeans"
  
  facetnames <- c(low="Low~Var", 
                     within="High~Var[Residual]", 
                     between="High~Var[Between~Neurons]",
                     pairmeans="High~Var[Pair~Means]"
                     )
  facetlabeller <- as_labeller(facetnames, label_parsed)
  
  
  alldat <- rbind(all_low, within, between, pairmeans)
  alldat$type <- factor(alldat$type, levels = c("low","within","between","pairmeans"))
  
  
  plt <- ggplot(alldat, aes(x=dependant, color = neuron_id, linetype = group)) + geom_density()
  plt <- plt + facet_wrap(facets = vars(type), labeller = facetlabeller)
  plt <- plt + labs(x="Amplitude/Frequency", y="Probability Density", linetype = "State", color = "Neuron")
  plt <- plt + theme(strip.text.x = element_text(size = 11), strip.text.y =  element_text(size = 11))
  return(plt)
}
