source("data_generation.r")

set.seed(0)

#' Generate gridded dataset draws
#'
#' @param nrows The number of columns
#' @param ncols The number of rows
#' @param paired Whether datasets should be paired or unpaired
#' @param ...  Additional arguments are passed on to gen_paired_data if paired=TRUE or gen_unpaired data otherwise
#'
#' @return data.frame
gen_gridded_dataset_draws <- function(nrows=3, ncols=3, paired = F, ...){
  rows = 1:nrows
  cols = 1:ncols
  
  between_neuron_vars <- seq(0.1,1,length=nrows)
  within_neuron_vars <- seq(0.1,1,length=ncols)
  
  datasets <- list()
  
  for (row in rows){
    for (col in cols){
      between <- between_neuron_vars[[row]]
      within <- within_neuron_vars[[col]]
      if(paired){
        dat<- gen_paired_data(interneuron_sd = sqrt(between), within_neuron_sd = sqrt(within), ...)
      }else{      
        dat<- gen_unpaired_data(control_group_interneuron_sd = sqrt(between), intervention_group_interneuron_sd = sqrt(between),
                                          control_within_neuron_sd = sqrt(within), intervention_within_neuron_sd = sqrt(within), ...)
      }

      
      dat$between_neuron_variance <- between
      dat$within_neuron_variance  <- within
      
      datasets[[(row-1)*length(cols) + col]] <- dat
    }
  }
  
  
  longform_datasets <- Reduce(rbind, datasets)
}

#' Plot Gridded Dataset Draws
#' 
#' A figure demonstrating how the data generated by data_generation.R functions can vary. 
#'
#' @param longform_datasets A set of gridded datasets generated by gen_gridded_dataset_draws
#' @param marginalize_neurons If TRUE, amalgamate neurons together. If FALSE, plot each neuron seperately
#' @param cumulative If TRUE, draw the empirical cumulative probability distribution. If False, draw the empirical probability density
#' @param paired Whether the data contained in longform_datasets is paired or unpaired
#'
#' @return ggplot object
plot_gridded_dataset_draws <- function(longform_datasets, marginalize_neurons = FALSE, cumulative = FALSE, paired = F){
  library(ggplot2)

  plt <- ggplot(data = longform_datasets, aes(x = dependant, color = group))
  
  if (marginalize_neurons && !cumulative){
    plt <- plt + geom_density()
  }else if (marginalize_neurons && cumulative){
    plt <- plt + stat_ecdf(geom="step")
  }else{
    if(paired){
      plt <- plt + geom_density(aes(color=neuron_id, linetype = group))
    }else{
      #Keep all the neurons in a group the same color
      for (neuron in unique(longform_datasets$neuron_id)){
        plt <- plt + geom_density(data = longform_datasets[longform_datasets$neuron_id == neuron,])
        
      }
    }
  }
  
  plt <- plt + facet_grid(rows                    = vars(between_neuron_variance),               cols = vars(within_neuron_variance), 
                          labeller = label_bquote(rows=Var[between]==.(between_neuron_variance), cols = Var[within]==.(within_neuron_variance)))
  plt <- plt + labs(x = "Amplitude or Frequency", y=if(cumulative)"Cumulative Probability" else "Probability Density")
  plt <- plt + theme(legend.title = element_blank())
  plt <- plt + theme(strip.text.x = element_text(size = 11), strip.text.y =  element_text(size = 11))
  return(plt)
}


show_treatment_effect_and_variance_difference <- function(marginalize_neurons = FALSE, cumulative = FALSE,...){
  

  
  no_treatment_effect <- gen_unpaired_data(treatment_effect = 0,
                                           control_within_neuron_sd = 1,
                                           intervention_within_neuron_sd = 1,
                                           ...)
  no_treatment_effect$type = "No Difference"
  treatment_effect <- gen_unpaired_data(treatment_effect = 2,
                                        control_within_neuron_sd = 1,
                                        intervention_within_neuron_sd = 1,
                                        ...)
  treatment_effect$type = "Different Means"
  variance_effect <- gen_unpaired_data(treatment_effect = 0,
                                       control_within_neuron_sd = 1,
                                       intervention_within_neuron_sd = 3,
                                       ...)
  variance_effect$type = "Different Standard Deviation"
  
  longform_datasets = rbind(no_treatment_effect, treatment_effect, variance_effect)
  
  longform_datasets$type <- factor(longform_datasets$type, c("No Difference", "Different Means", "Different Standard Deviation"))
  
  plt <- ggplot(data = longform_datasets, aes(x = dependant, color = group))
  
  if (marginalize_neurons && !cumulative){
    plt <- plt + geom_density()
  }else if (marginalize_neurons && cumulative){
    plt <- plt + stat_ecdf(geom="step")
  }else{
    for (neuron in unique(longform_datasets$neuron_id)){
      plt <- plt + geom_density(data = longform_datasets[longform_datasets$neuron_id == neuron,])
    }
  }
  plt <- plt + facet_grid(cols = vars(type), labeller = label_value)
  plt <- plt + theme(legend.title = element_blank(), panel.spacing.x = unit(4,"mm"))
  plt <- plt + labs(x = "Amplitude or Frequency", y = "Probability Density")
}
  

figure1 <- show_treatment_effect_and_variance_difference(n_control_neurons = 5, n_intervention_neurons = 5)

dat <- gen_gridded_dataset_draws(n_control_neurons = 6, n_intervention_neurons = 6, treatment_effect = 0)
figure2 <- plot_gridded_dataset_draws(dat, FALSE)
figure3 <- plot_gridded_dataset_draws(dat, TRUE, TRUE)
print(figure3)
#Make some figures of unpaired datasets with no treatment effect
dat <- gen_gridded_dataset_draws(treatment_effect = 0)
unmarginalized <- plot_gridded_dataset_draws(dat, FALSE)
cumulative     <- plot_gridded_dataset_draws(dat, TRUE, TRUE)
marginalized   <- plot_gridded_dataset_draws(dat, TRUE, FALSE)

#Make some figures of paired datasets with no treatment effect
paired_dat <- gen_gridded_dataset_draws(n_neurons = 3, treatment_effect = 0, paired = T, residual_interneuron_sd = 0.2)
paired_unmarginalized <- plot_gridded_dataset_draws(paired_dat, FALSE , paired = T)
paired_cumulative     <- plot_gridded_dataset_draws(paired_dat, TRUE, TRUE, paired = T)
paired_marginalized   <- plot_gridded_dataset_draws(paired_dat, TRUE, FALSE, paired = T)



